[project]
name = "portcast-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.1.3",
]
